version: '3.1'

services:
  mongo:
    image: mongo:4.4.10
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: practical
    volumes:
      - ./data/mongo:/data/db
      - ./dump:/dump
    ports:
      - 27017:27017